CREATE TABLE academic_years (
    academic_year CHAR(9),
    year_begin DATE,
    year_end DATE,
    intensive_I_begin DATE,
    intensive_I_end DATE,
    PI_begin DATE,
    PI_end DATE,
    exam_I_begin DATE,
    exam_I_end DATE,
    PII_begin DATE,
    PII_end DATE,
    exam_II_begin DATE,
    exam_II_end DATE,
    intensive_II_begin DATE,
    intensive_II_end DATE,
    PIII_begin DATE,
    PIII_end DATE,
    exam_III_begin DATE,
    exam_III_end DATE,
    PIV_begin DATE,
    PIV_end DATE,
    easter_break_begin DATE,
    easter_break end DATE,
    exam_IV_begin DATE,
    exam_IV_end DATE,
    intensive_III_begin DATE,
    intensive_III_end DATE
)